version: "2.1"

volumes:
  database:
  upload:

services:

  api:
    build:
      context: .
      dockerfile: deploy/api.docker
    ports:
      - 5000:5000
    depends_on:
        postgres:
            condition: service_healthy
    volumes:
      - ./api:/api
      - upload:/upload
    env_file:
      - deploy/api.env

  frontend:
    build:
      context: .
      dockerfile: deploy/frontend.docker
    command: yarn start
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/src/app
      - /src/app/node_modules
    env_file:
      - deploy/frontend.env

  postgres:
    image: postgres
    volumes:
      - database:/var/lib/postgresql/data/
    healthcheck:
        test: ["CMD", "pg_isready", "-U", "postgres"]
        interval: 2s
        timeout: 14s
        retries: 5
